### ISSUE TITLE
Getting unknown value

### ISSUE THREAD

**Issue by mikemix** [codeliner/array-reader#2]
How one can get a value if does not know what type of output to expect?

**Comment by codeliner** [comment]
Good question. Currently the ArrayReader doesn't provide such a function at least not a public one. I think I will add a getMixedValue method as soon as I have time. For now you can extend the ArrayReader and implement it yourself. Just call the protected function getValueFromPath($aPath) internally. Or you provide a PR :smiley:

**Comment by mikemix** [comment]
I already did it since I needed such feature in my library
https://github.com/mikemix/mxdiModule/blob/master/src/Annotation/InjectConfig.php

Your code is based on the fact that getValueFromPath() returns null. But what if the value of the requested key is null? :)

**Comment by codeliner** [comment]
> By the way, your code is based on the fact that getValueFromPath() returns null. But what if the value of the requested key is null? :)
I see no difference in requested key is not present or it has no value (aka set to null). In both cases the <type>Value methods convert the not existing value to an empty representation of the value: empty string, zero, false, etc.
But yeah, maybe I have to align it when adding the mixedValue method. Thx
